---
title: "IODS course project"
author: "Juho Mononen"
output:
  html_document:
    author: "Juho Mononen"
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
---

***

# Chapter 1 - Introduction to IODS course project

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  
***

# Chapter 2 - Regression and model validation  
```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

***

# Chapter 3 - Logistic regression
```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***

# Chapter 4 - Clustering and classification
```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

***

# Chapter 5 - Dimensionality reduction techniques
```{r child = "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

***

# Chapter 6 - Analysis of longitudinal data
```{r child = "chapter6.Rmd"}
# This will include Chapter 6 (that is updated in its own file) in the document.
```

***